#!/bin/bash
#set -x
# 
#edit: (lines 13-14)
#   pids = pids' name
#   services= lists of services related to pids
#
#run:
#   ./stop_services [all]


#Edit lists
pids=( "sshd" "cupsd" "mpd" "smbd" "nmbd" "avahi-daemon" )
services=( "ssh" "cups" "mpd" "smbd" "nmbd" "avahi-daemon" )


function check_pid {
    echo $2 | sudo -S pidof $1 > /dev/null 
    if [ $? -eq 0 ];
    then
       echo "  [RUNNING]" 
       return 0
    else
        echo "  [NOT RUNNING]"
        return 1
    fi
}

function stop_ss {
    echo $2 | sudo -S service $1 stop > /dev/null
    if [ $? ]; then
        echo -e "\t$1 [STOP]"
    else
        echo "Problems trying to stop $1..."
    fi
}

echo "Stopping services..."
if [ $UID -ne 0 ]; then
    user=$(sudo -n whoami 2>&1)
    if [ "$user" != "root" ]; then
        echo "Please input sudo password $(whoami):"
        read -s pass
    else
        pass=''
    fi
fi

for (( i=0 ; i<${#services[@]} ; i=$i+1 )); 
do
    pss=${pids[${i}]}
    ss=${services[${i}]}
    echo -n "Checking $ss"
    check_pid $pss $pass
    if [ $? -eq 0 ]; then
        if [ "$1" == "all" ]; then
            stop_ss $ss $pass
        else
            echo -en "\tWant to Stop $ss (y/n)[y]: "
            read op
            if [ "$op" == "y" ]; then
                stop_ss $ss $pass
            fi
        fi
    fi 
    echo
done

exit 0
